name: Run Test Harness
on:
  pull_request:
    branches: [main]
    paths:
      - "**.go"

jobs:
  harness-tests:
    name: Harness Tests
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: DevCycleHQ
          repo: test-harness
          github_token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
          workflow_file_name: config.yml
          ref: main
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          client_payload: '{ "sha": "${{ github.event.pull_request.head.sha }}", "sdk": "go", "title": "Go PR: ${{ github.event.pull_request.title }}" }'
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}
