/*
 * DevCycle Bucketing API
 *
 * Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package devcycle

import "time"

type DVCEvent struct {
	Type_       string                 `json:"type"`
	Target      string                 `json:"target,omitempty"`
	CustomType  string                 `json:"customType,omitempty"`
	UserId      string                 `json:"user_id,omitempty"`
	ClientDate  time.Time              `json:"clientDate,omitempty"`
	Value       float64                `json:"value,omitempty"`
	FeatureVars map[string]string      `json:"featureVars,omitempty"`
	MetaData    map[string]interface{} `json:"metaData,omitempty"`
}

type UserEventsBatchRecord struct {
	User   dvcPopulatedUser `json:"user"`
	Events []DVCEvent       `json:"events"`
}

type FlushPayload struct {
	PayloadId  string                  `json:"payloadId,omitempty"`
	EventCount int                     `json:"eventCount,omitempty"`
	Records    []UserEventsBatchRecord `json:"records,omitempty"`
}

type BatchEventsBody struct {
	Batch []UserEventsBatchRecord `json:"batch,omitempty"`
}
