/*
 * DevCycle Bucketing API
 *
 * Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package devcycle

import "time"

type DVCEvent struct {
	Type_       string                 `json:"type"`
	Target      string                 `json:"target"`
	CustomType  string                 `json:"customType"`
	UserId      string                 `json:"user_id"`
	ClientDate  time.Time              `json:"clientDate"`
	Value       float64                `json:"value"`
	FeatureVars map[string]string      `json:"featureVars"`
	MetaData    map[string]interface{} `json:"metaData"`
}

type UserEventsBatchRecord struct {
	User   dvcPopulatedUser `json:"user"`
	Events []DVCEvent       `json:"events"`
}

type FlushPayload struct {
	PayloadId  string                  `json:"payloadId"`
	EventCount int                     `json:"eventCount"`
	Records    []UserEventsBatchRecord `json:"records"`
}

type BatchEventsBody struct {
	Batch []UserEventsBatchRecord `json:"batch"`
}
