/*
 * DevCycle Bucketing API
 *
 * Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package devcycle

type Variable struct {
	ReadOnlyVariable
	// Default variable value can be a string, number, boolean, or JSON
	DefaultValue interface{} `json:"defaultValue"`
	// Identifies if variable was returned with the default value
	IsDefaulted bool `json:"isDefaulted,omitempty"`
}

type FeatureVariation struct {
	Feature   string `json:"_feature"`
	Variation string `json:"_variation"`
}

type ReadOnlyVariable struct {
	// unique database id
	Id string `json:"_id"`
	// Unique key by Project, can be used in the SDK / API to reference by 'key' rather than _id.
	Key string `json:"key"`
	// Variable type
	Type_ string `json:"type"`
	// Variable value can be a string, number, boolean, or JSON
	Value interface{} `json:"value"`
}
