/*
 * DevCycle Bucketing API
 *
 * Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package devcycle

type UserDataAndEventsBody struct {
	Events []Event `json:"events,omitempty"`
	User *UserData `json:"user,omitempty"`
}
