// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: proto/variableForUserParams.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariableType_PB int32

const (
	VariableType_PB_Boolean VariableType_PB = 0
	VariableType_PB_Number  VariableType_PB = 1
	VariableType_PB_String  VariableType_PB = 2
	VariableType_PB_JSON    VariableType_PB = 3
)

// Enum value maps for VariableType_PB.
var (
	VariableType_PB_name = map[int32]string{
		0: "Boolean",
		1: "Number",
		2: "String",
		3: "JSON",
	}
	VariableType_PB_value = map[string]int32{
		"Boolean": 0,
		"Number":  1,
		"String":  2,
		"JSON":    3,
	}
)

func (x VariableType_PB) Enum() *VariableType_PB {
	p := new(VariableType_PB)
	*p = x
	return p
}

func (x VariableType_PB) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableType_PB) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_variableForUserParams_proto_enumTypes[0].Descriptor()
}

func (VariableType_PB) Type() protoreflect.EnumType {
	return &file_proto_variableForUserParams_proto_enumTypes[0]
}

func (x VariableType_PB) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableType_PB.Descriptor instead.
func (VariableType_PB) EnumDescriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{0}
}

type CustomDataType int32

const (
	CustomDataType_Bool CustomDataType = 0
	CustomDataType_Num  CustomDataType = 1
	CustomDataType_Str  CustomDataType = 2
	CustomDataType_Null CustomDataType = 3
)

// Enum value maps for CustomDataType.
var (
	CustomDataType_name = map[int32]string{
		0: "Bool",
		1: "Num",
		2: "Str",
		3: "Null",
	}
	CustomDataType_value = map[string]int32{
		"Bool": 0,
		"Num":  1,
		"Str":  2,
		"Null": 3,
	}
)

func (x CustomDataType) Enum() *CustomDataType {
	p := new(CustomDataType)
	*p = x
	return p
}

func (x CustomDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_variableForUserParams_proto_enumTypes[1].Descriptor()
}

func (CustomDataType) Type() protoreflect.EnumType {
	return &file_proto_variableForUserParams_proto_enumTypes[1]
}

func (x CustomDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomDataType.Descriptor instead.
func (CustomDataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{1}
}

type NullableString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNull bool   `protobuf:"varint,2,opt,name=isNull,proto3" json:"isNull,omitempty"`
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{0}
}

func (x *NullableString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NullableString) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

type NullableDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNull bool    `protobuf:"varint,2,opt,name=isNull,proto3" json:"isNull,omitempty"`
}

func (x *NullableDouble) Reset() {
	*x = NullableDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDouble) ProtoMessage() {}

func (x *NullableDouble) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDouble.ProtoReflect.Descriptor instead.
func (*NullableDouble) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{1}
}

func (x *NullableDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NullableDouble) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

type CustomDataValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        CustomDataType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.CustomDataType" json:"type,omitempty"`
	BoolValue   bool           `protobuf:"varint,2,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DoubleValue float64        `protobuf:"fixed64,3,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	StringValue string         `protobuf:"bytes,4,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
}

func (x *CustomDataValue) Reset() {
	*x = CustomDataValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomDataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomDataValue) ProtoMessage() {}

func (x *CustomDataValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomDataValue.ProtoReflect.Descriptor instead.
func (*CustomDataValue) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{2}
}

func (x *CustomDataValue) GetType() CustomDataType {
	if x != nil {
		return x.Type
	}
	return CustomDataType_Bool
}

func (x *CustomDataValue) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *CustomDataValue) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *CustomDataValue) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

type NullableCustomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  map[string]*CustomDataValue `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsNull bool                        `protobuf:"varint,2,opt,name=isNull,proto3" json:"isNull,omitempty"`
}

func (x *NullableCustomData) Reset() {
	*x = NullableCustomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableCustomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableCustomData) ProtoMessage() {}

func (x *NullableCustomData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableCustomData.ProtoReflect.Descriptor instead.
func (*NullableCustomData) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{3}
}

func (x *NullableCustomData) GetValue() map[string]*CustomDataValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NullableCustomData) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

type VariableForUserParams_PB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SdkKey           string          `protobuf:"bytes,1,opt,name=sdkKey,proto3" json:"sdkKey,omitempty"`
	VariableKey      string          `protobuf:"bytes,2,opt,name=variableKey,proto3" json:"variableKey,omitempty"`
	VariableType     VariableType_PB `protobuf:"varint,3,opt,name=variableType,proto3,enum=proto.VariableType_PB" json:"variableType,omitempty"`
	User             *DVCUser_PB     `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ShouldTrackEvent bool            `protobuf:"varint,5,opt,name=shouldTrackEvent,proto3" json:"shouldTrackEvent,omitempty"`
}

func (x *VariableForUserParams_PB) Reset() {
	*x = VariableForUserParams_PB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableForUserParams_PB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableForUserParams_PB) ProtoMessage() {}

func (x *VariableForUserParams_PB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableForUserParams_PB.ProtoReflect.Descriptor instead.
func (*VariableForUserParams_PB) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{4}
}

func (x *VariableForUserParams_PB) GetSdkKey() string {
	if x != nil {
		return x.SdkKey
	}
	return ""
}

func (x *VariableForUserParams_PB) GetVariableKey() string {
	if x != nil {
		return x.VariableKey
	}
	return ""
}

func (x *VariableForUserParams_PB) GetVariableType() VariableType_PB {
	if x != nil {
		return x.VariableType
	}
	return VariableType_PB_Boolean
}

func (x *VariableForUserParams_PB) GetUser() *DVCUser_PB {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *VariableForUserParams_PB) GetShouldTrackEvent() bool {
	if x != nil {
		return x.ShouldTrackEvent
	}
	return false
}

type DVCUser_PB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            string              `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email             *NullableString     `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name              *NullableString     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language          *NullableString     `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Country           *NullableString     `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	AppBuild          *NullableDouble     `protobuf:"bytes,6,opt,name=appBuild,proto3" json:"appBuild,omitempty"`
	AppVersion        *NullableString     `protobuf:"bytes,7,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	DeviceModel       *NullableString     `protobuf:"bytes,8,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	CustomData        *NullableCustomData `protobuf:"bytes,9,opt,name=customData,proto3" json:"customData,omitempty"`
	PrivateCustomData *NullableCustomData `protobuf:"bytes,10,opt,name=privateCustomData,proto3" json:"privateCustomData,omitempty"`
}

func (x *DVCUser_PB) Reset() {
	*x = DVCUser_PB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DVCUser_PB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DVCUser_PB) ProtoMessage() {}

func (x *DVCUser_PB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DVCUser_PB.ProtoReflect.Descriptor instead.
func (*DVCUser_PB) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{5}
}

func (x *DVCUser_PB) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DVCUser_PB) GetEmail() *NullableString {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *DVCUser_PB) GetName() *NullableString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DVCUser_PB) GetLanguage() *NullableString {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *DVCUser_PB) GetCountry() *NullableString {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *DVCUser_PB) GetAppBuild() *NullableDouble {
	if x != nil {
		return x.AppBuild
	}
	return nil
}

func (x *DVCUser_PB) GetAppVersion() *NullableString {
	if x != nil {
		return x.AppVersion
	}
	return nil
}

func (x *DVCUser_PB) GetDeviceModel() *NullableString {
	if x != nil {
		return x.DeviceModel
	}
	return nil
}

func (x *DVCUser_PB) GetCustomData() *NullableCustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

func (x *DVCUser_PB) GetPrivateCustomData() *NullableCustomData {
	if x != nil {
		return x.PrivateCustomData
	}
	return nil
}

type SDKVariable_PB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XId         string          `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Type        VariableType_PB `protobuf:"varint,2,opt,name=type,proto3,enum=proto.VariableType_PB" json:"type,omitempty"`
	Key         string          `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	BoolValue   bool            `protobuf:"varint,4,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DoubleValue float64         `protobuf:"fixed64,5,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	StringValue string          `protobuf:"bytes,6,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	EvalReason  *NullableString `protobuf:"bytes,7,opt,name=evalReason,proto3" json:"evalReason,omitempty"`
}

func (x *SDKVariable_PB) Reset() {
	*x = SDKVariable_PB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_variableForUserParams_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDKVariable_PB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDKVariable_PB) ProtoMessage() {}

func (x *SDKVariable_PB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_variableForUserParams_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDKVariable_PB.ProtoReflect.Descriptor instead.
func (*SDKVariable_PB) Descriptor() ([]byte, []int) {
	return file_proto_variableForUserParams_proto_rawDescGZIP(), []int{6}
}

func (x *SDKVariable_PB) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *SDKVariable_PB) GetType() VariableType_PB {
	if x != nil {
		return x.Type
	}
	return VariableType_PB_Boolean
}

func (x *SDKVariable_PB) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SDKVariable_PB) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *SDKVariable_PB) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *SDKVariable_PB) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *SDKVariable_PB) GetEvalReason() *NullableString {
	if x != nil {
		return x.EvalReason
	}
	return nil
}

var File_proto_variableForUserParams_proto protoreflect.FileDescriptor

var file_proto_variableForUserParams_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0e, 0x4e, 0x75,
	0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x3e, 0x0a, 0x0e, 0x4e, 0x75,
	0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x9e, 0x01, 0x0a, 0x0f, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x6f,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x12,
	0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x50, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe3, 0x01, 0x0a, 0x18, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x5f, 0x50, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x64, 0x6b, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x64, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x3a, 0x0a, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x50, 0x42, 0x52, 0x0c, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x56, 0x43, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x50, 0x42, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x68,
	0x6f, 0x75, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x88,
	0x04, 0x0a, 0x0a, 0x44, 0x56, 0x43, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x50, 0x42, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75,
	0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x31, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x61, 0x70, 0x70,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x47, 0x0a, 0x11, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x11, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0xf8, 0x01, 0x0a, 0x0e, 0x53, 0x44,
	0x4b, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x50, 0x42, 0x12, 0x0f, 0x0a, 0x03,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x50, 0x42, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x65, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x40, 0x0a, 0x0f, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x50, 0x42, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x03, 0x2a, 0x36, 0x0a, 0x0e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53,
	0x74, 0x72, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x10, 0x03, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_variableForUserParams_proto_rawDescOnce sync.Once
	file_proto_variableForUserParams_proto_rawDescData = file_proto_variableForUserParams_proto_rawDesc
)

func file_proto_variableForUserParams_proto_rawDescGZIP() []byte {
	file_proto_variableForUserParams_proto_rawDescOnce.Do(func() {
		file_proto_variableForUserParams_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_variableForUserParams_proto_rawDescData)
	})
	return file_proto_variableForUserParams_proto_rawDescData
}

var file_proto_variableForUserParams_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_variableForUserParams_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_variableForUserParams_proto_goTypes = []interface{}{
	(VariableType_PB)(0),             // 0: proto.VariableType_PB
	(CustomDataType)(0),              // 1: proto.CustomDataType
	(*NullableString)(nil),           // 2: proto.NullableString
	(*NullableDouble)(nil),           // 3: proto.NullableDouble
	(*CustomDataValue)(nil),          // 4: proto.CustomDataValue
	(*NullableCustomData)(nil),       // 5: proto.NullableCustomData
	(*VariableForUserParams_PB)(nil), // 6: proto.VariableForUserParams_PB
	(*DVCUser_PB)(nil),               // 7: proto.DVCUser_PB
	(*SDKVariable_PB)(nil),           // 8: proto.SDKVariable_PB
	nil,                              // 9: proto.NullableCustomData.ValueEntry
}
var file_proto_variableForUserParams_proto_depIdxs = []int32{
	1,  // 0: proto.CustomDataValue.type:type_name -> proto.CustomDataType
	9,  // 1: proto.NullableCustomData.value:type_name -> proto.NullableCustomData.ValueEntry
	0,  // 2: proto.VariableForUserParams_PB.variableType:type_name -> proto.VariableType_PB
	7,  // 3: proto.VariableForUserParams_PB.user:type_name -> proto.DVCUser_PB
	2,  // 4: proto.DVCUser_PB.email:type_name -> proto.NullableString
	2,  // 5: proto.DVCUser_PB.name:type_name -> proto.NullableString
	2,  // 6: proto.DVCUser_PB.language:type_name -> proto.NullableString
	2,  // 7: proto.DVCUser_PB.country:type_name -> proto.NullableString
	3,  // 8: proto.DVCUser_PB.appBuild:type_name -> proto.NullableDouble
	2,  // 9: proto.DVCUser_PB.appVersion:type_name -> proto.NullableString
	2,  // 10: proto.DVCUser_PB.deviceModel:type_name -> proto.NullableString
	5,  // 11: proto.DVCUser_PB.customData:type_name -> proto.NullableCustomData
	5,  // 12: proto.DVCUser_PB.privateCustomData:type_name -> proto.NullableCustomData
	0,  // 13: proto.SDKVariable_PB.type:type_name -> proto.VariableType_PB
	2,  // 14: proto.SDKVariable_PB.evalReason:type_name -> proto.NullableString
	4,  // 15: proto.NullableCustomData.ValueEntry.value:type_name -> proto.CustomDataValue
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_variableForUserParams_proto_init() }
func file_proto_variableForUserParams_proto_init() {
	if File_proto_variableForUserParams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_variableForUserParams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_variableForUserParams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_variableForUserParams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomDataValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_variableForUserParams_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableCustomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_variableForUserParams_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableForUserParams_PB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_variableForUserParams_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DVCUser_PB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_variableForUserParams_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDKVariable_PB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_variableForUserParams_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_variableForUserParams_proto_goTypes,
		DependencyIndexes: file_proto_variableForUserParams_proto_depIdxs,
		EnumInfos:         file_proto_variableForUserParams_proto_enumTypes,
		MessageInfos:      file_proto_variableForUserParams_proto_msgTypes,
	}.Build()
	File_proto_variableForUserParams_proto = out.File
	file_proto_variableForUserParams_proto_rawDesc = nil
	file_proto_variableForUserParams_proto_goTypes = nil
	file_proto_variableForUserParams_proto_depIdxs = nil
}
