name: Test Examples
## For anyone looking to change this (Internal to DevCycle) - the project is here: https://app.devcycle.com/o/org_U9F8YMaTChTEndWw/p/git-hub-actions-integration-tests/features/6642210af1c941418857b237
on:
  pull_request:
    branches: [main]

jobs:
  test_examples:
    name: Test Examples
    runs-on: ubuntu-latest
    env:
      DEVCYCLE_SERVER_SDK_KEY: dvc_server_token_hash
      DEVCYCLE_VARIABLE_KEY: test
    strategy:
      matrix:
        example:
          - example/local
          - example/cloud
          - example/openfeature
          - example/hooks
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run example ${{ matrix.example }}
        run: go run ./${{ matrix.example }}
        continue-on-error: true
